# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QWidget)

from kmap.controller.tabwidget import TabWidget

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        if not mainwindow.objectName():
            mainwindow.setObjectName(u"mainwindow")
        mainwindow.resize(800, 600)
        self.open_sim_tab_action = QAction(mainwindow)
        self.open_sim_tab_action.setObjectName(u"open_sim_tab_action")
        self.load_cube_file_action = QAction(mainwindow)
        self.load_cube_file_action.setObjectName(u"load_cube_file_action")
        self.load_cube_online_action = QAction(mainwindow)
        self.load_cube_online_action.setObjectName(u"load_cube_online_action")
        self.show_matplotlib = QAction(mainwindow)
        self.show_matplotlib.setObjectName(u"show_matplotlib")
        self.log_file_action = QAction(mainwindow)
        self.log_file_action.setObjectName(u"log_file_action")
        self.mod_log_file_action = QAction(mainwindow)
        self.mod_log_file_action.setObjectName(u"mod_log_file_action")
        self.general_action = QAction(mainwindow)
        self.general_action.setObjectName(u"general_action")
        self.general_default_action = QAction(mainwindow)
        self.general_default_action.setObjectName(u"general_default_action")
        self.logging_action = QAction(mainwindow)
        self.logging_action.setObjectName(u"logging_action")
        self.logging_default_action = QAction(mainwindow)
        self.logging_default_action.setObjectName(u"logging_default_action")
        self.settings_action = QAction(mainwindow)
        self.settings_action.setObjectName(u"settings_action")
        self.readme_action = QAction(mainwindow)
        self.readme_action.setObjectName(u"readme_action")
        self.welcome_action = QAction(mainwindow)
        self.welcome_action.setObjectName(u"welcome_action")
        self.about_action = QAction(mainwindow)
        self.about_action.setObjectName(u"about_action")
        self.ref_action = QAction(mainwindow)
        self.ref_action.setObjectName(u"ref_action")
        self.load_hdf5_action = QAction(mainwindow)
        self.load_hdf5_action.setObjectName(u"load_hdf5_action")
        self.load_sliced_from_binding_energy_action = QAction(mainwindow)
        self.load_sliced_from_binding_energy_action.setObjectName(u"load_sliced_from_binding_energy_action")
        self.load_sliced_from_photon_energy_action = QAction(mainwindow)
        self.load_sliced_from_photon_energy_action.setObjectName(u"load_sliced_from_photon_energy_action")
        self.open_profile_tab_action = QAction(mainwindow)
        self.open_profile_tab_action.setObjectName(u"open_profile_tab_action")
        self.open_lmfit_tab_action = QAction(mainwindow)
        self.open_lmfit_tab_action.setObjectName(u"open_lmfit_tab_action")
        self.rename_current_tab_action = QAction(mainwindow)
        self.rename_current_tab_action.setObjectName(u"rename_current_tab_action")
        self.export_txt = QAction(mainwindow)
        self.export_txt.setObjectName(u"export_txt")
        self.load_sliced_from_cubefile_action = QAction(mainwindow)
        self.load_sliced_from_cubefile_action.setObjectName(u"load_sliced_from_cubefile_action")
        self.duplicate_tab_action = QAction(mainwindow)
        self.duplicate_tab_action.setObjectName(u"duplicate_tab_action")
        self.close_tab_action = QAction(mainwindow)
        self.close_tab_action.setObjectName(u"close_tab_action")
        self.save_project_action = QAction(mainwindow)
        self.save_project_action.setObjectName(u"save_project_action")
        self.load_project_action = QAction(mainwindow)
        self.load_project_action.setObjectName(u"load_project_action")
        self.export_hdf5 = QAction(mainwindow)
        self.export_hdf5.setObjectName(u"export_hdf5")
        self.open_splitview_tab_action = QAction(mainwindow)
        self.open_splitview_tab_action.setObjectName(u"open_splitview_tab_action")
        self.shortcut_action = QAction(mainwindow)
        self.shortcut_action.setObjectName(u"shortcut_action")
        self.shortcut_default_action = QAction(mainwindow)
        self.shortcut_default_action.setObjectName(u"shortcut_default_action")
        self.export_numpy = QAction(mainwindow)
        self.export_numpy.setObjectName(u"export_numpy")
        self.central_widget = QWidget(mainwindow)
        self.central_widget.setObjectName(u"central_widget")
        self.horizontalLayout = QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.tab_widget = TabWidget(self.central_widget)
        self.tab_widget.setObjectName(u"tab_widget")

        self.horizontalLayout.addWidget(self.tab_widget)

        mainwindow.setCentralWidget(self.central_widget)
        self.menubar = QMenuBar(mainwindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.cube_menu = QMenu(self.file_menu)
        self.cube_menu.setObjectName(u"cube_menu")
        self.export_menu = QMenu(self.file_menu)
        self.export_menu.setObjectName(u"export_menu")
        self.log_menu = QMenu(self.file_menu)
        self.log_menu.setObjectName(u"log_menu")
        self.load_hdf5_menu = QMenu(self.file_menu)
        self.load_hdf5_menu.setObjectName(u"load_hdf5_menu")
        self.edit_menu = QMenu(self.menubar)
        self.edit_menu.setObjectName(u"edit_menu")
        self.settings_menu = QMenu(self.menubar)
        self.settings_menu.setObjectName(u"settings_menu")
        self.general_menu = QMenu(self.settings_menu)
        self.general_menu.setObjectName(u"general_menu")
        self.logging_menu = QMenu(self.settings_menu)
        self.logging_menu.setObjectName(u"logging_menu")
        self.shortcut_menu = QMenu(self.settings_menu)
        self.shortcut_menu.setObjectName(u"shortcut_menu")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setObjectName(u"help_menu")
        mainwindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.settings_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.file_menu.addAction(self.load_hdf5_menu.menuAction())
        self.file_menu.addAction(self.cube_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.save_project_action)
        self.file_menu.addAction(self.load_project_action)
        self.file_menu.addAction(self.export_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.log_menu.menuAction())
        self.cube_menu.addAction(self.load_cube_file_action)
        self.cube_menu.addAction(self.load_cube_online_action)
        self.export_menu.addAction(self.show_matplotlib)
        self.export_menu.addAction(self.export_txt)
        self.export_menu.addAction(self.export_hdf5)
        self.export_menu.addAction(self.export_numpy)
        self.log_menu.addAction(self.log_file_action)
        self.log_menu.addAction(self.mod_log_file_action)
        self.load_hdf5_menu.addAction(self.load_hdf5_action)
        self.load_hdf5_menu.addAction(self.load_sliced_from_binding_energy_action)
        self.load_hdf5_menu.addAction(self.load_sliced_from_photon_energy_action)
        self.load_hdf5_menu.addAction(self.load_sliced_from_cubefile_action)
        self.edit_menu.addAction(self.open_sim_tab_action)
        self.edit_menu.addAction(self.open_profile_tab_action)
        self.edit_menu.addAction(self.open_lmfit_tab_action)
        self.edit_menu.addAction(self.open_splitview_tab_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.duplicate_tab_action)
        self.edit_menu.addAction(self.close_tab_action)
        self.settings_menu.addAction(self.general_menu.menuAction())
        self.settings_menu.addAction(self.logging_menu.menuAction())
        self.settings_menu.addAction(self.shortcut_menu.menuAction())
        self.settings_menu.addSeparator()
        self.settings_menu.addAction(self.settings_action)
        self.general_menu.addAction(self.general_action)
        self.general_menu.addAction(self.general_default_action)
        self.logging_menu.addAction(self.logging_action)
        self.logging_menu.addAction(self.logging_default_action)
        self.shortcut_menu.addAction(self.shortcut_action)
        self.shortcut_menu.addAction(self.shortcut_default_action)
        self.help_menu.addAction(self.readme_action)
        self.help_menu.addAction(self.welcome_action)
        self.help_menu.addAction(self.about_action)

        self.retranslateUi(mainwindow)

        QMetaObject.connectSlotsByName(mainwindow)
    # setupUi

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(QCoreApplication.translate("mainwindow", u"MainWindow", None))
        self.open_sim_tab_action.setText(QCoreApplication.translate("mainwindow", u"Open new Orbital Tab", None))
        self.load_cube_file_action.setText(QCoreApplication.translate("mainwindow", u"Locally...", None))
        self.load_cube_online_action.setText(QCoreApplication.translate("mainwindow", u"Online...", None))
        self.show_matplotlib.setText(QCoreApplication.translate("mainwindow", u"Matplotlib", None))
        self.log_file_action.setText(QCoreApplication.translate("mainwindow", u"default.log...", None))
        self.mod_log_file_action.setText(QCoreApplication.translate("mainwindow", u"module.log", None))
        self.general_action.setText(QCoreApplication.translate("mainwindow", u"Edit User", None))
        self.general_default_action.setText(QCoreApplication.translate("mainwindow", u"Show Default", None))
        self.logging_action.setText(QCoreApplication.translate("mainwindow", u"Edit User", None))
        self.logging_default_action.setText(QCoreApplication.translate("mainwindow", u"Show Default", None))
        self.settings_action.setText(QCoreApplication.translate("mainwindow", u"Reload Settings", None))
        self.readme_action.setText(QCoreApplication.translate("mainwindow", u"Open README", None))
        self.welcome_action.setText(QCoreApplication.translate("mainwindow", u"Open Welcome", None))
        self.about_action.setText(QCoreApplication.translate("mainwindow", u"About kMap.py", None))
        self.ref_action.setText(QCoreApplication.translate("mainwindow", u"Print References", None))
        self.load_hdf5_action.setText(QCoreApplication.translate("mainwindow", u"Locally...", None))
        self.load_sliced_from_binding_energy_action.setText(QCoreApplication.translate("mainwindow", u"From Orbitals ...", None))
        self.load_sliced_from_photon_energy_action.setText(QCoreApplication.translate("mainwindow", u"From hnu-dependence ...", None))
        self.open_profile_tab_action.setText(QCoreApplication.translate("mainwindow", u"Open new Profile Tab", None))
        self.open_lmfit_tab_action.setText(QCoreApplication.translate("mainwindow", u"Open new LM-Fit Tab", None))
        self.rename_current_tab_action.setText(QCoreApplication.translate("mainwindow", u"Rename current Tab", None))
        self.export_txt.setText(QCoreApplication.translate("mainwindow", u"Textfile", None))
#if QT_CONFIG(tooltip)
        self.export_txt.setToolTip(QCoreApplication.translate("mainwindow", u"Exports the contents of the current tab, if possible, as .txt file.\n"
"\n"
"Currently the profile plot and the lmfit plot tab support this feature.", None))
#endif // QT_CONFIG(tooltip)
        self.load_sliced_from_cubefile_action.setText(QCoreApplication.translate("mainwindow", u"From Cubefile ...", None))
        self.duplicate_tab_action.setText(QCoreApplication.translate("mainwindow", u"Duplicate current Tab", None))
        self.close_tab_action.setText(QCoreApplication.translate("mainwindow", u"Close current Tab", None))
        self.save_project_action.setText(QCoreApplication.translate("mainwindow", u"Save Project...", None))
        self.load_project_action.setText(QCoreApplication.translate("mainwindow", u"Load Project...", None))
        self.export_hdf5.setText(QCoreApplication.translate("mainwindow", u"Hdf5", None))
        self.open_splitview_tab_action.setText(QCoreApplication.translate("mainwindow", u"Open new Split-View Tab", None))
        self.shortcut_action.setText(QCoreApplication.translate("mainwindow", u"Edit User", None))
        self.shortcut_default_action.setText(QCoreApplication.translate("mainwindow", u"Show Default", None))
        self.export_numpy.setText(QCoreApplication.translate("mainwindow", u"Numpy", None))
        self.file_menu.setTitle(QCoreApplication.translate("mainwindow", u"File", None))
        self.cube_menu.setTitle(QCoreApplication.translate("mainwindow", u"Load Orbital Data...", None))
        self.export_menu.setTitle(QCoreApplication.translate("mainwindow", u"Export", None))
        self.log_menu.setTitle(QCoreApplication.translate("mainwindow", u"Open .log Files...", None))
        self.load_hdf5_menu.setTitle(QCoreApplication.translate("mainwindow", u"Load Sliced Data...", None))
        self.edit_menu.setTitle(QCoreApplication.translate("mainwindow", u"Tabs", None))
        self.settings_menu.setTitle(QCoreApplication.translate("mainwindow", u"Preferences", None))
        self.general_menu.setTitle(QCoreApplication.translate("mainwindow", u"General Settings", None))
        self.logging_menu.setTitle(QCoreApplication.translate("mainwindow", u"Logging Settings", None))
        self.shortcut_menu.setTitle(QCoreApplication.translate("mainwindow", u"Shortcut Settings", None))
        self.help_menu.setTitle(QCoreApplication.translate("mainwindow", u"Help", None))
    # retranslateUi

